### PR TITLE
Script for importing official title translations

### PR DESCRIPTION
**Pull request by brockfanning**

### CODE REVIEW

**Comment by brockfanning** [comment]
@JenPark9 Here is the results of importing the official titles. It unfortunately changes a ton more than just the title lines, so it's a bit hard to review the changes. But as discussed, the excess changes are only harmless line-length changes.

**Comment by brockfanning** [comment]
@JenPark9 I'm going to see if I can work the 1.1.1a/1.1.1b problem into the script. Are there any other indicators like that?

**Comment by JenPark9** [comment]
Tier 1
1.1.1a, 1.1.1b, 2.2.2a, 2.2.2b, 4.1.1a, 4.1.1bc, 5.5.1a, 5.5.1b, 6.6.1a,
6.6.1b, 17.3.1a, 17.3.1b
Tier 2
1.3.1a, 1.3.1b,12.3.1a, 12.3.1b
16.6.2 has an annex 1 and an annex 2. I haven't prepared those templates
yet. I need to double check if these should be named 16.6.2 a and b.

**Comment by brockfanning** [comment]
@JenPark9 Ok, I've added support for these split indicators into this script, so there should be no manual steps necessary after merging this.

**Pull request merged**
